version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: tennis-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    restart: unless-stopped
    networks:
      - tennis-network

  redis:
    image: redis:7.0-alpine
    container_name: tennis-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass password
    restart: unless-stopped
    networks:
      - tennis-network

  vault:
    image: hashicorp/vault:1.13
    container_name: tennis-vault
    ports:
      - "8200:8200"
    volumes:
      - vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=dev-token
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_ADDR=http://0.0.0.0:8200
    command: server -dev -dev-root-token-id=dev-token
    restart: unless-stopped
    networks:
      - tennis-network

volumes:
  mongodb_data:
  redis_data:
  vault_data:

networks:
  tennis-network:
    driver: bridge 