# Backend Environment Variables - Generated by Vault Agent
{{- with secret "kv/data/tennisapp/prod/database" }}
MONGO_URI="mongodb://{{ .Data.data.username }}:{{ .Data.data.password }}@mongodb:27017/{{ .Data.data.database }}?authSource=admin"
MONGO_DB_NAME="{{ .Data.data.database }}"
{{- end }}

{{- with secret "kv/data/tennisapp/prod/redis" }}
REDIS_ADDR="redis:6379"
REDIS_PASSWORD="{{ .Data.data.password }}"
REDIS_DB=0
{{- end }}

{{- with secret "kv/data/tennisapp/prod/jwt" }}
JWT_SECRET="{{ .Data.data.secret }}"
{{- end }}

{{- with secret "kv/data/tennisapp/prod/email" }}
GMAIL_EMAIL="{{ .Data.data.email }}"
GMAIL_PASSWORD="{{ .Data.data.password }}"
{{- end }}

# Vault Configuration
VAULT_ADDR=http://vault:8200

# Application Configuration
API_PORT=8080
DB_NAME=tennis_booking 