name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: apps/backend/go.sum
      
      - name: Install dependencies
        run: cd apps/backend && go mod download
      
      - name: Run tests
        run: cd apps/backend && go test ./... -v
  
  scraper-tests:
    name: Scraper Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: apps/scraper/requirements.txt
      
      - name: Install dependencies
        run: |
          cd apps/scraper
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright browsers
        run: |
          cd apps/scraper
          python -m playwright install --with-deps chromium
      
      - name: Run tests
        run: |
          cd apps/scraper
          python -m pytest tests/ 