name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-tests:
    name: Backend Tests
    runs-on: ubuntu-latest
    
    services:
      mongodb:
        image: mongo:6
        ports:
          - 27017:27017
      redis:
        image: redis:7
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          cache: true
          cache-dependency-path: apps/backend/go.sum
      
      - name: Install dependencies
        run: cd apps/backend && go mod download
      
      - name: Run tests
        run: cd apps/backend && go test ./... -v

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-reports
          path: |
            apps/backend/coverage.out
            apps/backend/coverage.html
          retention-days: 7

  frontend-tests:
    name: Frontend Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: apps/frontend/package-lock.json
      
      - name: Install dependencies
        run: |
          cd apps/frontend
          npm ci
      
      - name: Run linting
        run: |
          cd apps/frontend
          npm run lint
      
      - name: Build application
        run: |
          cd apps/frontend
          npm run build
      
      # TODO: Add tests when they exist
      # - name: Run tests
      #   run: |
      #     cd apps/frontend  
      #     npm test
  
  scraper-tests:
    name: Scraper Tests
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: apps/scraper/requirements.txt
      
      - name: Install dependencies
        run: |
          cd apps/scraper
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Install Playwright browsers
        run: |
          cd apps/scraper
          python -m playwright install --with-deps chromium
      
      - name: Run tests
        run: |
          cd apps/scraper
          python -m pytest tests/ 

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for secret scanning
      
      - name: Check commit count
        id: check_commits
        run: |
          COMMIT_COUNT=$(git rev-list --count HEAD)
          echo "commit_count=$COMMIT_COUNT" >> $GITHUB_OUTPUT
          echo "has_previous_commit=$([[ $COMMIT_COUNT -gt 1 ]] && echo true || echo false)" >> $GITHUB_OUTPUT
      
      - name: Run Secret Scan (Pull Request)
        if: github.event_name == 'pull_request'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified
      
      - name: Run Secret Scan (Push to Main - Diff)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_commits.outputs.has_previous_commit == 'true'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: HEAD~1
          head: HEAD
          extra_args: --debug --only-verified
          
      - name: Run Secret Scan (Push to Main - Full Scan for Initial Commit)
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' && steps.check_commits.outputs.has_previous_commit == 'false'
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          extra_args: --debug --only-verified 